### ISSUE TITLE
Not combining files

### ISSUE THREAD

**Issue by gr8rck** [bite-your-idols/Combiner#1]
Not able to get this to work in Sublime Text 3 by doing the following:

-  Created a file called /combiner-styles.css (as output)
-  Created 3 additional css files /css-file1.css,..file2.css...file3.css
- Added to top of combiner-style.css:

/*
Combiner:{
  combine:"M:\CSS_Projects\XXX\main.styles.css",
  combine:"M:\CSS_Projects\XXX\medical.styles.css",
  combine:"M:\CSS_Projects\XXX\sport.styles.css",  
  output:"M:\CSS_Projects\XXX\combiner-file.css"
}
*/

Ran 'combiner' command from both dropdown menu and shortcut.  no output.

Maybe just missing a step or executing incorrectly.  

Please advise.

Ryan.

**Comment by bite-your-idols** [comment]
It seems it is something related with your path... did you tried using a local path? if all css files are in the same folder and also combiner declaration file is, you can try this:
```
/*
Combiner:{
combine:"main.styles.css",
combine:"medical.styles.css",
combine:"sport.styles.css",
output:"combiner-file.css"
}
*/
```

You can also check what is happening by opening Sublime's console, then run Combiner. If something is wrong it should be output there.

**Comment by gr8rck** [comment]
Yes, moving to a relative path seems to have fixed the problem.  Everything works great.

We can mark this resolved and thanks for the assistance!

Thanks,
Ryan.
