### ISSUE TITLE
Only absolute path

### ISSUE THREAD

**Issue by Spica2** [bite-your-idols/Combiner#2]
Accespts only absolute path from /Users/...

````
File "/Users/username/Library/Application Support/Sublime Text 3/Installed Packages/Combiner.sublime-package/Combiner.py", line 70, in run
FileNotFoundError: [Errno 2] No such file or directory: 'main.js'

**Comment by bite-your-idols** [comment]
I would like to see the file where your combiner declaration is located.

**Comment by Spica2** [comment]
as simple as this:
```
/*
Combiner:{
  combine:"main.js",
  output:"main-comb.js"
}
*/

**Comment by bite-your-idols** [comment]
and the file where this declaration is located in the same folder as "main.js"?

can you please paste here the absolute path? maybe it contains any kind of ugly characters...

**Comment by Spica2** [comment]
Both in same folder
/Users/username/Documents/folder-Git/folder/Res-JS/main.js
With absolute Pathnames it is outputing correctly. So it should not be a chars issue

**Comment by bite-your-idols** [comment]
it is weird... I tried it with absolute, relative, network paths and everything works ok...
did you tried to place your files folder in another location or drive?
does sublime text console output something else?

**Comment by Spica2** [comment]
Saw your response late.
Only have this:
```Traceback (most recent call last):
  File "/Programme OSX/WebDev/Sublime Text 3.app/Contents/MacOS/sublime_plugin.py", line 1072, in run_
    return self.run(edit)```
Sublime is located in a different folder than "programms", but this should not have any effect.

**Comment by bite-your-idols** [comment]
did you tried to place your files folder in another location or drive?

**Comment by kat0d** [comment]
for me it's does not work at all
/*
Combiner: {
  combine:"blog.js",
  combine:"jquery-main.js",
  output:"all.file.js"
}
*/

try to combine, and nothing happens
windows10
sublime 3

**Comment by bite-your-idols** [comment]
what is the output in console (view>show console)?

**Comment by bltzr** [comment]
Hi!

I tried using your plugin, and it also fails.

Here’s the Combiner block:
```
Combiner:{
  combine:"max.js",
  combine:"scenes.js",
  combine:"tracks.js",
  combine:"params.js",
  combine:"selection.js",
  combine:"utils.js",
  output:"../MMM.js"
}
```

And here’s the console output:
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1494, in run_
    return self.run(edit)
  File "/Users/bltzr/Library/Application Support/Sublime Text 3/Installed Packages/Combiner.sublime-package/Combiner.py", line 11, in run
AttributeError: 'NoneType' object has no attribute 'split'
```

(I also tried with absolute patrs, with no avail)

Sublime Build 4126, stable channel, MacOS 11.2.3
